env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 
  - 'eslint:recommended'
  - 'plugin:mocha/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
rules: {}
plugins:
  - mocha
